name: Generate Datas

on:
  schedule: # Executa automaticamente a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente a qualquer momento

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Gera a animação da cobrinha (Versão v3 mais atual)
      - name: generate-github-contribution-grid-snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Envia os arquivos gerados para a branch 'output'
      - name: push github-contribution-grid-snake to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: false # <--- ADICIONE ESTA LINHA AQUI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
